### ISSUE TITLE
OrderingLite-Backend

### ISSUE THREAD

**Issue by lionel2425** [dextercai/OrderingLite-FrontEnd#1]
您好 ， 想问一下这个点餐系统前后端搭建起来后 如何登入呀 一直提示 
非法桌台，请向服务员询问  或者 验证不正确    ，用数据库的账号密码也不行

**Comment by dextercai** [comment]
感谢您开启第一个Issue，我不清楚您详细的报错，但根据我的印象，请您注意这几个问题。    
1. 数据库内的密码经过散列加密，算法是BCRYPT，PHP自带，具体请参考后端本处：https://github.com/dextercai/OrderingLite-Backend/blob/9ad674fe80493c039bf2f3e631514891ed6c7944/app/controller/User.php#L34
2. 桌台需要用一个验证码才能访问，这个在后台开台之后可以直接看到。    
3. 注意CORS问题

BTW，因为我完成大作业之后并没有留下一些截图之类的，如果您愿意，欢迎给本Repo提一个PR，放一些界面截图。

**Comment by lionel2425** [comment]
![image](https://user-images.githubusercontent.com/58417488/141435202-eb8caae7-78a6-42cd-9e91-db84e7a3e6dc.png)
这是截图 我不太会上传照片 请问你看得到吗， 还有个问题就是 前端项目是需要放在后端项目public路径下 还是说根目录下

**Comment by lionel2425** [comment]
![image](https://user-images.githubusercontent.com/58417488/141438541-fcae3f5d-6b56-482d-b04d-b83854e16681.png)
这是项目目录

**Comment by dextercai** [comment]
https://github.com/dextercai/OrderingLite-FrontEnd/blob/905b5df5e2311454e8b89f3936ed6ec517f91598/src/utils/request.js#L5

具体的请求URL拼接在这个地方，基本上就是对axios简单包装，你可以直接修改此处的逻辑。

我估计你的nginx或者apache的设置存在问题。TP5.0开始 你的web访问根目录应该是public，所以按照你截图的这个部署方式是错误的。

**Comment by lionel2425** [comment]
![image](https://user-images.githubusercontent.com/58417488/141441251-8fce7d49-918a-470c-9746-1341dde8ee04.png)
1.这个我已经修改了我本地地址 
2.我刚刚已经安照您说的设置访问public为根目录，但是好像访问不到后端。
![image](https://user-images.githubusercontent.com/58417488/141443929-131bd5b2-49ba-4ec3-b275-e1c22b86461b.png)

![image](https://user-images.githubusercontent.com/58417488/141443791-ed79c048-776a-4429-8df8-cbb6eec086ec.png)

3.然后请问您之前说的后台开台之后 获取的验证码 我要如何查看呢 是在数据库还是存储呀，谢谢您的耐心解答，我还是个小白

**Comment by dextercai** [comment]
验证码直接在开台功能那边就有显示。
我看了你的截图，怀疑可能你的构建存在问题。正常不应该会是这样的。
出现后端链路错误的情况，建议去看一眼CORS，加入后端白名单内，具体应该是在middleware下。

**Comment by lionel2425** [comment]
![image](https://user-images.githubusercontent.com/58417488/141707546-e9fa8080-a28b-41d6-8971-6b82b1553a98.png)
我把CORS设置和前端一样 也没有任何变化 
但是我看了下代码 会不会是url拼接问题呀
![image](https://user-images.githubusercontent.com/58417488/141707689-cfeb99a9-abdb-4b33-bc3f-7fba5d05e82a.png)
正常不是应该是 http://localhost:8080/login 之类的吗

**Comment by dextercai** [comment]
那你试一下把入口点从index.php改成api.php吧，然后重设一下baseurl。我之前作业实施的时候是前后端分离，绑在两个域名上。可能对应的你需要调一些伪静态规则。
